name: Build Android (and IOS) APP

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Delete Assets/Videos folder before Unity build
        run: |
          echo "Removing Assets/Videos directory to prevent import errors"
          rm -rf ./Assets/Videos

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android
          restore-keys: |
            Library-

      - uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Build-Android
          path: build/Android
