name: Build Unity iOS and Export IPA

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Unity
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/unity3d
          ~/.local/share/unity3d
        key: ${{ runner.os }}-unity

    - name: Build iOS with Unity
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: iOS

    # ----------------------------
    # CODE SIGNING SETUP
    # ----------------------------

    - name: Install signing certificate
      run: |
        echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
        security create-keychain -p "buildpass" build.keychain
        security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "buildpass" build.keychain
        security set-keychain-settings build.keychain
      env:
        IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_P12_CERTIFICATE }}
        CERT_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}

    - name: Install provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$IOS_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
      env:
        IOS_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}

    # ----------------------------
    # BUILD IPA WITH XCODEBUILD
    # ----------------------------

    - name: Install CocoaPods (optional)
      run: |
        cd build/iOS
        pod install || echo "No Podfile"

    - name: Archive the app
      run: |
        mkdir -p build/output

        xcodebuild \
          -workspace build/iOS/Unity-iPhone.xcworkspace \
          -scheme Unity-iPhone \
          -configuration Release \
          -archivePath build/output/Unity-iPhone.xcarchive \
          archive \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER=AAS-Distribution-profile \
          DEVELOPMENT_TEAM=NDK28GDYKQ \
          CODE_SIGN_IDENTITY="iPhone Distribution"

    - name: Export IPA
      run: |
        cat <<EOF > ExportOptions.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" \
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>ad-hoc</string>
          <key>signingStyle</key>
          <string>manual</string>
          <key>provisioningProfiles</key>
          <dict>
            <key>com.epyphite.aas-companion-app</key>
            <string>AAS-Distribution-profile</string>
          </dict>
          <key>teamID</key>
          <string>NDK28GDYKQ</string>
          <key>compileBitcode</key>
          <false/>
        </dict>
        </plist>
        EOF

        xcodebuild \
          -exportArchive \
          -archivePath build/output/Unity-iPhone.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/output

    - name: Upload .ipa artifact
      uses: actions/upload-artifact@v3
      with:
        name: Unity-iOS-App
        path: build/output/*.ipa
