name: Build iOS App

on:
  push:
    branches:
      - main
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - '.github/**'

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Delete Assets/Videos folder before Unity build
        run: |
          echo "Removing Assets/Videos directory to prevent import errors"
          rm -rf ./Assets/Videos

      - name: Git LFS Pull
        run: |
          git lfs pull
          git reset --hard

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-iOS-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}

      - name: Build iOS with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS

      - name: Create Gemfile
        run: |
          mkdir -p ios-fastlane
          echo 'source "https://rubygems.org"
          gem "fastlane", "~> 2.227.1"
          gem "faraday", "< 1.10"
          gem "xcodeproj"' > ios-fastlane/Gemfile

      - name: Set up Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Fastlane using Bundler
        run: |
          cd ios-fastlane
          bundle install

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_P12_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          ls ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Force Manual Signing in Xcode project
        run: |
          ruby <<'RUBY'
            require 'xcodeproj'
          
            project_path = 'build/iOS/iOS/Unity-iPhone.xcodeproj'
            project = Xcodeproj::Project.open(project_path)
          
            project.targets.each do |target|
              next if target.name == 'UnityFramework' 
              puts "Setting manual signing for target: #{target.name}"
              target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
                config.build_settings['DEVELOPMENT_TEAM'] = 'NDK28GDYKQ'
                config.build_settings['CODE_SIGN_IDENTITY'] = 'Apple Distribution'
                config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'AAS-Distribuiton-App-Store'
                config.build_settings.delete('CODE_SIGN_IDENTITY[sdk=iphoneos*]')
                config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]')
              end
            end
            project.save
          RUBY

      - name: Generate Fastfile
        run: |
          mkdir -p ios-fastlane/fastlane
          echo 'default_platform(:ios)
          platform :ios do
            desc "Build IPA from Unity Xcode project"
            lane :build_ipa do
              build_app(
                project: "../build/iOS/iOS/Unity-iPhone.xcodeproj",
                scheme: "Unity-iPhone",
                export_method: "app-store",
                export_options: {
                  method: "app-store",
                  signingStyle: "manual",
                  teamID: "NDK28GDYKQ"
                },
                clean: true,
                output_directory: "./output",
                output_name: "UnityApp.ipa"
              )
            end
          
            desc "Upload to TestFlight"
            lane :upload_to_testflight do
              app_store_connect_api_key(
                key_id: ENV["APPSTORE_API_KEY_ID"],
                issuer_id: ENV["APPSTORE_ISSUER_ID"],
                key_content: ENV["APPSTORE_API_PRIVATE_KEY"],
                duration: 1200,
                in_house: false
              )
              upload_to_testflight(
                skip_waiting_for_build_processing: true,
                ipa: "./output/UnityApp.ipa"
              )
            end
          end' > ios-fastlane/fastlane/Fastfile

      - name: Build IPA with Fastlane
        run: |
          cd ios-fastlane
          bundle exec fastlane build_ipa
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-IPA
          path: ios-fastlane/output/UnityApp.ipa

      - name: Upload to TestFlight with Fastlane
        run: |
          cd ios-fastlane
          bundle exec fastlane upload_to_testflight
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPSTORE_API_KEY_ID: ${{ vars.APPSTORE_API_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
          APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
